apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
spec:
  type: NodePort
  selector:
    app: expense-tracker
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30036
